SET FOREIGN_KEY_CHECKS = 0;  

DELETE FROM PRICES;
DELETE FROM SERVICES;
ALTER TABLE SERVICES AUTO_INCREMENT = 1;

DELETE FROM GUESTRECEPTION;
DELETE FROM GUESTS;
ALTER TABLE GUESTS AUTO_INCREMENT = 1;

DELETE FROM USERLOGS;
ALTER TABLE USERLOGS AUTO_INCREMENT = 1;

DELETE FROM ROOM;
ALTER TABLE ROOM AUTO_INCREMENT = 1;

DELETE FROM BUILDING;
ALTER TABLE BUILDING AUTO_INCREMENT = 1;

DELETE FROM ASSIGNMENT;
ALTER TABLE ASSIGNMENT AUTO_INCREMENT = 1;

DELETE FROM ACCESSCARD;
ALTER TABLE ACCESSCARD AUTO_INCREMENT = 1;

DELETE FROM `USER`;
ALTER TABLE `USER` AUTO_INCREMENT = 1;

TRUNCATE TABLE GEO_INFO;
TRUNCATE TABLE CARDCHECKS;
TRUNCATE TABLE SUBSCRIPTIONS;
TRUNCATE TABLE PLACEMENT;

SET FOREIGN_KEY_CHECKS = 1;  
